### ISSUE TITLE
Bug Report: slow healthbar

### ISSUE THREAD

**Issue by guizinhomartinez** [TheCyVap/FNF-NR#1]
it's not exactly a bug but i wanted to know how you you maked the healthbar go slow
and how i code this in kade engine

**Comment by TheCyVap** [comment]
All I really did was replace the Kade Engine health loss and gain values in PlayState.hx with the FNF ones found in normal FNF's source code.

That and I added code to holding sustain notes to make it so they heal you like in actual FNF.

**Comment by guizinhomartinez** [comment]
ok but what line i get these
